### ISSUE TITLE
Fix small typo in `save_to_images()` docstring

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomolib#11]
Just a small typo I came across, since it shows itself in the [deployed API docs](https://diamondlightsource.github.io/httomolib/api/httomolib.misc.images.html) (should be `offset`, not `offest`): https://github.com/DiamondLightSource/httomolib/blob/eab881480b5f277085f0113b234c01c8ccca16ec/httomolib/misc/images.py#L90

**Comment by dkazanc** [comment]
fix in
