### ISSUE TITLE
removing subsubfolder in imagesaver

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomolib#18]
It was raised on [Jira](https://jira.diamond.ac.uk/browse/HTTOMO-37) if we need to have the subsubfolder created [here](https://github.com/DiamondLightSource/httomolib/blob/1fe392b837a707d41d30b7301df520cd7fa4b3d1/httomolib/misc/images.py#L105C5-L105C22). I guess, this can be a bit redundant indeed as the main information given in that folder name is the bit used for images. This can be parsed to folder name above instead? Shall we make the structure shallower?

**Comment by yousefmoazzam** [comment]
Yeah, I agree with the feedback that the extra subfolder is redundant, so getting rid of the unnecessary extra layer sounds good to me.

**Comment by dkazanc** [comment]
I'll try and do that change then, hopefully it won't break too many tests in httomo
